# config/database.yml
default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["DB_USERNAME"] || "glenY" %>
  password: <%= ENV["DB_PASSWORD"] || "Passw0rdis1234_." %>
  host: <%= ENV["DB_HOST"] || "192.168.31.91" %>
  port: <%= ENV["DB_PORT"] || 1433 %>
  database: <%= ENV["DB_NAME"] || "railsTest" %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DB_NAME"] || "railsTest_test" %>

production:
  <<: *default